// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/session.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TypstSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession;

  @protected
  TypstSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    dynamic raw,
  );

  @protected
  TypstSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    dynamic raw,
  );

  @protected
  TypstSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HighlightTag dco_decode_box_autoadd_highlight_tag(dynamic raw);

  @protected
  SessionOptions dco_decode_box_autoadd_session_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CompileResult dco_decode_compile_result(dynamic raw);

  @protected
  DiagnosticSeverity dco_decode_diagnostic_severity(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HighlightNode dco_decode_highlight_node(dynamic raw);

  @protected
  HighlightTag dco_decode_highlight_tag(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LinkData dco_decode_link_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<HighlightNode> dco_decode_list_highlight_node(dynamic raw);

  @protected
  List<LinkData> dco_decode_list_link_data(dynamic raw);

  @protected
  List<PageInfo> dco_decode_list_page_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RectPt> dco_decode_list_rect_pt(dynamic raw);

  @protected
  List<TextFragmentData> dco_decode_list_text_fragment_data(dynamic raw);

  @protected
  List<TypstDiagnostic> dco_decode_list_typst_diagnostic(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HighlightTag? dco_decode_opt_box_autoadd_highlight_tag(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PageInfo dco_decode_page_info(dynamic raw);

  @protected
  PageTextData dco_decode_page_text_data(dynamic raw);

  @protected
  RectPt dco_decode_rect_pt(dynamic raw);

  @protected
  RenderedRegion dco_decode_rendered_region(dynamic raw);

  @protected
  SessionOptions dco_decode_session_options(dynamic raw);

  @protected
  TextFragmentData dco_decode_text_fragment_data(dynamic raw);

  @protected
  TypstDiagnostic dco_decode_typst_diagnostic(dynamic raw);

  @protected
  TypstrxError dco_decode_typstrx_error(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  TypstSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    SseDeserializer deserializer,
  );

  @protected
  TypstSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    SseDeserializer deserializer,
  );

  @protected
  TypstSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HighlightTag sse_decode_box_autoadd_highlight_tag(
    SseDeserializer deserializer,
  );

  @protected
  SessionOptions sse_decode_box_autoadd_session_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CompileResult sse_decode_compile_result(SseDeserializer deserializer);

  @protected
  DiagnosticSeverity sse_decode_diagnostic_severity(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HighlightNode sse_decode_highlight_node(SseDeserializer deserializer);

  @protected
  HighlightTag sse_decode_highlight_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LinkData sse_decode_link_data(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<HighlightNode> sse_decode_list_highlight_node(
    SseDeserializer deserializer,
  );

  @protected
  List<LinkData> sse_decode_list_link_data(SseDeserializer deserializer);

  @protected
  List<PageInfo> sse_decode_list_page_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RectPt> sse_decode_list_rect_pt(SseDeserializer deserializer);

  @protected
  List<TextFragmentData> sse_decode_list_text_fragment_data(
    SseDeserializer deserializer,
  );

  @protected
  List<TypstDiagnostic> sse_decode_list_typst_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HighlightTag? sse_decode_opt_box_autoadd_highlight_tag(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer);

  @protected
  PageTextData sse_decode_page_text_data(SseDeserializer deserializer);

  @protected
  RectPt sse_decode_rect_pt(SseDeserializer deserializer);

  @protected
  RenderedRegion sse_decode_rendered_region(SseDeserializer deserializer);

  @protected
  SessionOptions sse_decode_session_options(SseDeserializer deserializer);

  @protected
  TextFragmentData sse_decode_text_fragment_data(SseDeserializer deserializer);

  @protected
  TypstDiagnostic sse_decode_typst_diagnostic(SseDeserializer deserializer);

  @protected
  TypstrxError sse_decode_typstrx_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    TypstSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    TypstSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    TypstSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_highlight_tag(
    HighlightTag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_options(
    SessionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_compile_result(CompileResult self, SseSerializer serializer);

  @protected
  void sse_encode_diagnostic_severity(
    DiagnosticSeverity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_highlight_node(HighlightNode self, SseSerializer serializer);

  @protected
  void sse_encode_highlight_tag(HighlightTag self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_link_data(LinkData self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_highlight_node(
    List<HighlightNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_link_data(List<LinkData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_info(List<PageInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rect_pt(List<RectPt> self, SseSerializer serializer);

  @protected
  void sse_encode_list_text_fragment_data(
    List<TextFragmentData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_typst_diagnostic(
    List<TypstDiagnostic> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_highlight_tag(
    HighlightTag? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_page_text_data(PageTextData self, SseSerializer serializer);

  @protected
  void sse_encode_rect_pt(RectPt self, SseSerializer serializer);

  @protected
  void sse_encode_rendered_region(
    RenderedRegion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_options(
    SessionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_text_fragment_data(
    TextFragmentData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_typst_diagnostic(
    TypstDiagnostic self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_typstrx_error(TypstrxError self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstSession(
    int ptr,
  );
}
