// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `map_diagnostics`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Compiled`, `SessionInner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TypstSession>>
abstract class TypstSession implements RustOpaqueInterface {
  /// Compiles `source` as the main file.
  ///
  /// On success the result carries a new generation and the page sizes; on
  /// failure the previous document (if any) remains valid and renderable.
  /// Diagnostics (errors and warnings) are always included.
  Future<CompileResult> compile({required String source});

  /// Computes completions at `cursor_utf16` in the source as of the last
  /// `compile()` call (successful or not). See [`CompletionResult`] for
  /// why it isn't computed against whatever the caller's live buffer
  /// currently holds, and how to detect when the two have diverged.
  Future<CompletionResult> completions({
    required int cursorUtf16,
    required bool explicit,
  });

  /// Creates a new session. Fonts embedded in the library are available
  /// immediately; additional fonts can be added with [`register_font`].
  static Future<TypstSession> create({required SessionOptions options}) =>
      RustLib.instance.api.crateApiSessionTypstSessionCreate(options: options);

  /// Exports the latest compiled document as vector PDF bytes.
  ///
  /// Fails with [`TypstrxError::Stale`] when `generation` no longer matches
  /// the latest compiled document. The returned PDF retains Typst's vector
  /// paths, fonts, text, links, and other native PDF resources.
  Future<Uint8List> exportPdf({required BigInt generation});

  /// Computes folding ranges for `source` — collapsible regions like code
  /// blocks, content blocks, argument lists, array/dict literals, and
  /// block comments that span more than one line. See
  /// [`crate::folding`] for why headings aren't included.
  ///
  /// Independent of compilation, like [`Self::highlight`]. Unlike
  /// [`Self::completions`]/[`Self::hover`], there is no `generation` to
  /// check: the result is computed directly from `source`, not the
  /// World's own registered one, so it's already current for whatever the
  /// caller passes.
  Future<List<TypstFoldingRange>> foldingRanges({required String source});

  /// Looks up documentation for the function named `label`, for an
  /// IntelliSense-style details panel shown alongside the completion list.
  ///
  /// `cursor_utf16` is used first, to resolve whatever's actually at that
  /// position in the source as of the last `compile()` call (handles field
  /// access like `calc.abs`, local functions, etc.); if that doesn't
  /// resolve to a function, falls back to a plain lookup of `label` in the
  /// global scope (handles browsing completions before a full expression
  /// exists, e.g. `#re|`). See [`CompletionResult`] for what `generation`
  /// means.
  Future<FunctionInfoResult> functionInfo({
    required int cursorUtf16,
    required String label,
  });

  /// Computes a syntax-highlighting tree for `source`.
  ///
  /// Independent of compilation: this only parses, so it touches neither
  /// the session's lock nor its incremental-compile state, and cannot
  /// contend with an in-flight compile or render. Safe to call on every
  /// keystroke.
  Future<HighlightNode> highlight({required String source});

  /// Computes a hover tooltip at `cursor_utf16` in the source as of the
  /// last `compile()` call. See [`CompletionResult`] for what `generation`
  /// means and why this doesn't use the caller's live buffer directly.
  Future<HoverResult> hover({required int cursorUtf16});

  /// Extracts text and link geometry for page `page_index` (0-based).
  ///
  /// Fails with [`TypstrxError::Stale`] when `generation` no longer matches
  /// the latest compiled document.
  Future<PageTextData> pageText({
    required BigInt generation,
    required int pageIndex,
  });

  /// Registers all font faces contained in `data` (TTF/OTF, also
  /// collections). Returns the number of faces added. Takes effect on the
  /// next compilation.
  Future<int> registerFont({required List<int> data});

  /// Renders the window `(x, y, width, height)` in pixels out of page
  /// `page_index` (0-based) rasterized at a virtual full size of
  /// `full_width` × `full_height` pixels.
  ///
  /// Fails with [`TypstrxError::Stale`] when `generation` no longer matches
  /// the latest compiled document; callers should drop the request then.
  Future<RenderedRegion> renderPageRegion({
    required BigInt generation,
    required int pageIndex,
    required int x,
    required int y,
    required int width,
    required int height,
    required int fullWidth,
    required int fullHeight,
    required int backgroundArgb,
  });

  /// Adds or replaces an in-memory project file (image, bibliography,
  /// module, …) that the main source can reference by `path`.
  Future<void> setFile({required String path, required List<int> data});
}
