// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `map_diagnostics`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Compiled`, `SessionInner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TypstSession>>
abstract class TypstSession implements RustOpaqueInterface {
  /// Compiles `source` as the main file.
  ///
  /// On success the result carries a new generation and the page sizes; on
  /// failure the previous document (if any) remains valid and renderable.
  /// Diagnostics (errors and warnings) are always included.
  Future<CompileResult> compile({required String source});

  /// Creates a new session. Fonts embedded in the library are available
  /// immediately; additional fonts can be added with [`register_font`].
  static Future<TypstSession> create({required SessionOptions options}) =>
      RustLib.instance.api.crateApiSessionTypstSessionCreate(options: options);

  /// Computes a syntax-highlighting tree for `source`.
  ///
  /// Independent of compilation: this only parses, so it touches neither
  /// the session's lock nor its incremental-compile state, and cannot
  /// contend with an in-flight compile or render. Safe to call on every
  /// keystroke.
  Future<HighlightNode> highlight({required String source});

  /// Extracts text and link geometry for page `page_index` (0-based).
  ///
  /// Fails with [`TypstrxError::Stale`] when `generation` no longer matches
  /// the latest compiled document.
  Future<PageTextData> pageText({
    required BigInt generation,
    required int pageIndex,
  });

  /// Registers all font faces contained in `data` (TTF/OTF, also
  /// collections). Returns the number of faces added. Takes effect on the
  /// next compilation.
  Future<int> registerFont({required List<int> data});

  /// Renders the window `(x, y, width, height)` in pixels out of page
  /// `page_index` (0-based) rasterized at a virtual full size of
  /// `full_width` × `full_height` pixels.
  ///
  /// Fails with [`TypstrxError::Stale`] when `generation` no longer matches
  /// the latest compiled document; callers should drop the request then.
  Future<RenderedRegion> renderPageRegion({
    required BigInt generation,
    required int pageIndex,
    required int x,
    required int y,
    required int width,
    required int height,
    required int fullWidth,
    required int fullHeight,
    required int backgroundArgb,
  });

  /// Adds or replaces an in-memory project file (image, bibliography,
  /// module, …) that the main source can reference by `path`.
  Future<void> setFile({required String path, required List<int> data});
}
