// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The outcome of a compilation. Returned for both successful and failed
/// compiles; `success` tells them apart and `diagnostics` carries errors and
/// warnings in both cases.
class CompileResult {
  /// Identifies the compiled document. Subsequent render/text calls must
  /// pass this value and fail with [`TypstrxError::Stale`] once a newer
  /// compilation has completed.
  final BigInt generation;

  /// Whether a document was produced. On failure the previous document (if
  /// any) stays available under its own generation.
  final bool success;

  /// Per-page sizes of the compiled document. Empty on failure.
  final List<PageInfo> pages;

  /// Errors and warnings emitted by the compiler.
  final List<TypstDiagnostic> diagnostics;

  /// Wall-clock compilation time in milliseconds.
  final BigInt elapsedMs;

  const CompileResult({
    required this.generation,
    required this.success,
    required this.pages,
    required this.diagnostics,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      generation.hashCode ^
      success.hashCode ^
      pages.hashCode ^
      diagnostics.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          success == other.success &&
          pages == other.pages &&
          diagnostics == other.diagnostics &&
          elapsedMs == other.elapsedMs;
}

/// The result of computing completions at a cursor position.
///
/// Completions are analyzed against the source as of the last `compile()`
/// call (successful or not) — value-aware completions (e.g. field access)
/// need the World's own registered `Source` to resolve, which only reflects
/// edits once they have gone through `compile()`. `generation` identifies
/// that state: compare it against the `generation` of the document
/// currently displayed (from the last successful `compile()`) and discard
/// the result if they don't match, rather than applying `apply_from_utf16`
/// against a buffer it wasn't computed for.
class CompletionResult {
  /// The generation this analysis ran against.
  final BigInt generation;

  /// Where the completions apply from, in UTF-16 code units. Applying a
  /// completion means replacing the source range from this offset to the
  /// cursor with the chosen [`TypstCompletion::apply`].
  final int applyFromUtf16;
  final List<TypstCompletion> completions;

  const CompletionResult({
    required this.generation,
    required this.applyFromUtf16,
    required this.completions,
  });

  @override
  int get hashCode =>
      generation.hashCode ^ applyFromUtf16.hashCode ^ completions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletionResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          applyFromUtf16 == other.applyFromUtf16 &&
          completions == other.completions;
}

/// Severity of a [`TypstDiagnostic`].
enum DiagnosticSeverity { error, warning }

/// The result of looking up a function's documentation. See
/// [`CompletionResult`] for what `generation` means and why it's needed.
class FunctionInfoResult {
  final BigInt generation;
  final TypstFunctionInfo? info;

  const FunctionInfoResult({required this.generation, this.info});

  @override
  int get hashCode => generation.hashCode ^ info.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FunctionInfoResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          info == other.info;
}

/// One node of a syntax-highlighting tree for Typst source.
///
/// Mirrors the shape of the parse tree: a node with `children` is a grouping
/// construct (e.g. strong emphasis, a heading) and its own `text` is empty; a
/// node with no children is a leaf and `text` is its literal source text.
/// Concatenating every leaf's `text` in tree order reproduces the exact
/// source that was highlighted, so offsets never need to cross the bridge —
/// a caller can track them by summing leaf text lengths while walking.
class HighlightNode {
  /// The highlighting category, if any. `None` for plain/ungrouped nodes.
  final HighlightTag? tag;

  /// This node's literal text, non-empty only for leaves.
  final String text;

  /// Child nodes, non-empty only for non-leaves.
  final List<HighlightNode> children;

  const HighlightNode({this.tag, required this.text, required this.children});

  @override
  int get hashCode => tag.hashCode ^ text.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightNode &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          text == other.text &&
          children == other.children;
}

/// A syntax-highlighting category, mirroring `typst_syntax::Tag`.
enum HighlightTag {
  comment,
  punctuation,
  escape,
  strong,
  emph,
  link,
  raw,
  label,
  ref,
  heading,
  listMarker,
  listTerm,
  mathDelimiter,
  mathOperator,
  mathGroupingParens,
  keyword,
  operator_,
  number,
  string,
  function,
  interpolated,
  error,
}

/// The result of computing a hover tooltip. See [`CompletionResult`] for
/// what `generation` means and why it's needed.
class HoverResult {
  final BigInt generation;
  final TypstTooltip? tooltip;

  const HoverResult({required this.generation, this.tooltip});

  @override
  int get hashCode => generation.hashCode ^ tooltip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoverResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          tooltip == other.tooltip;
}

/// A link region on a page. Either `url` or the `dest_*` fields are set.
class LinkData {
  final RectPt rect;

  /// External URL, if this is a web link.
  final String? url;

  /// Target page (1-based) for an internal link.
  final int? destPage;

  /// Target x position on the destination page in points.
  final double? destXPt;

  /// Target y position on the destination page in points.
  final double? destYPt;

  const LinkData({
    required this.rect,
    this.url,
    this.destPage,
    this.destXPt,
    this.destYPt,
  });

  @override
  int get hashCode =>
      rect.hashCode ^
      url.hashCode ^
      destPage.hashCode ^
      destXPt.hashCode ^
      destYPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkData &&
          runtimeType == other.runtimeType &&
          rect == other.rect &&
          url == other.url &&
          destPage == other.destPage &&
          destXPt == other.destXPt &&
          destYPt == other.destYPt;
}

/// Size of a single page in typographic points (1/72 inch).
class PageInfo {
  final double widthPt;
  final double heightPt;

  const PageInfo({required this.widthPt, required this.heightPt});

  @override
  int get hashCode => widthPt.hashCode ^ heightPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          widthPt == other.widthPt &&
          heightPt == other.heightPt;
}

/// Text and link geometry of one page.
class PageTextData {
  /// The page's text in visual reading order, lines separated by `\n`.
  final String fullText;

  /// One rect per UTF-16 code unit of `full_text` (so the list indexes the
  /// text as a Dart `String`). Newline separators have zero-width rects.
  final List<RectPt> charRects;

  /// Consecutive runs of `full_text` with their bounds; fragments cover the
  /// whole text without gaps.
  final List<TextFragmentData> fragments;

  /// Links on the page.
  final List<LinkData> links;

  const PageTextData({
    required this.fullText,
    required this.charRects,
    required this.fragments,
    required this.links,
  });

  @override
  int get hashCode =>
      fullText.hashCode ^
      charRects.hashCode ^
      fragments.hashCode ^
      links.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageTextData &&
          runtimeType == other.runtimeType &&
          fullText == other.fullText &&
          charRects == other.charRects &&
          fragments == other.fragments &&
          links == other.links;
}

/// A rectangle in page coordinates: typographic points, top-left origin,
/// y-down (`top <= bottom`).
class RectPt {
  final double left;
  final double top;
  final double right;
  final double bottom;

  const RectPt({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ right.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RectPt &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}

/// A rendered tile of a page: premultiplied RGBA8888 pixels, `width * height * 4`
/// bytes, rows top-to-bottom.
class RenderedRegion {
  final int width;
  final int height;
  final Uint8List pixels;

  const RenderedRegion({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderedRegion &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// Configuration for creating a Typst session.
class SessionOptions {
  /// Directory where downloaded `@preview` packages are cached. When `None`,
  /// the platform's standard Typst cache directory is used (which may not be
  /// writable on mobile platforms — pass an app-specific directory there).
  final String? packageCacheDir;

  /// Whether `@preview` packages may be downloaded from the network. Cached
  /// packages keep working when this is `false`.
  final bool allowPackageDownload;

  const SessionOptions({
    this.packageCacheDir,
    required this.allowPackageDownload,
  });

  static Future<SessionOptions> default_() =>
      RustLib.instance.api.crateApiTypesSessionOptionsDefault();

  @override
  int get hashCode => packageCacheDir.hashCode ^ allowPackageDownload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOptions &&
          runtimeType == other.runtimeType &&
          packageCacheDir == other.packageCacheDir &&
          allowPackageDownload == other.allowPackageDownload;
}

/// A text run: `full_text[index..index + length]` (UTF-16 indices).
class TextFragmentData {
  final int index;
  final int length;
  final RectPt bounds;

  const TextFragmentData({
    required this.index,
    required this.length,
    required this.bounds,
  });

  @override
  int get hashCode => index.hashCode ^ length.hashCode ^ bounds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextFragmentData &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          length == other.length &&
          bounds == other.bounds;
}

/// An autocompletion option.
class TypstCompletion {
  final TypstCompletionKind kind;

  /// The text shown in the completion list.
  final String label;

  /// The text to insert, already defaulted to `label` when Typst didn't
  /// supply one. May contain snippet placeholders like `${name}` or an
  /// empty tab stop `${}`; there is no numbering — stops are visited in
  /// the order they appear in the string.
  final String apply;

  /// An optional one-sentence description.
  final String? detail;

  const TypstCompletion({
    required this.kind,
    required this.label,
    required this.apply,
    this.detail,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ label.hashCode ^ apply.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstCompletion &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label &&
          apply == other.apply &&
          detail == other.detail;
}

@freezed
sealed class TypstCompletionKind with _$TypstCompletionKind {
  const TypstCompletionKind._();

  const factory TypstCompletionKind.syntax() = TypstCompletionKind_Syntax;
  const factory TypstCompletionKind.func() = TypstCompletionKind_Func;
  const factory TypstCompletionKind.type() = TypstCompletionKind_Type;
  const factory TypstCompletionKind.param() = TypstCompletionKind_Param;
  const factory TypstCompletionKind.constant() = TypstCompletionKind_Constant;
  const factory TypstCompletionKind.path() = TypstCompletionKind_Path;
  const factory TypstCompletionKind.package() = TypstCompletionKind_Package;
  const factory TypstCompletionKind.label() = TypstCompletionKind_Label;
  const factory TypstCompletionKind.font() = TypstCompletionKind_Font;

  /// A symbol (e.g. a math shorthand). `notation` is its literal
  /// shorthand/name, not user-facing text.
  const factory TypstCompletionKind.symbol({required String notation}) =
      TypstCompletionKind_Symbol;
}

/// A compiler error or warning.
///
/// Source positions are only resolved for spans that point into the main
/// source (not into packages or other files) and are `None` otherwise.
/// `utf16_start`/`utf16_end` index the main source as a Dart `String`.
class TypstDiagnostic {
  final DiagnosticSeverity severity;
  final String message;
  final List<String> hints;

  /// Start offset into the main source in UTF-16 code units.
  final int? utf16Start;

  /// End offset into the main source in UTF-16 code units.
  final int? utf16End;

  /// 1-based line of the start offset.
  final int? line;

  /// 1-based column (in UTF-16 code units) of the start offset.
  final int? column;

  const TypstDiagnostic({
    required this.severity,
    required this.message,
    required this.hints,
    this.utf16Start,
    this.utf16End,
    this.line,
    this.column,
  });

  @override
  int get hashCode =>
      severity.hashCode ^
      message.hashCode ^
      hints.hashCode ^
      utf16Start.hashCode ^
      utf16End.hashCode ^
      line.hashCode ^
      column.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstDiagnostic &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          message == other.message &&
          hints == other.hints &&
          utf16Start == other.utf16Start &&
          utf16End == other.utf16End &&
          line == other.line &&
          column == other.column;
}

/// What kind of construct a [`TypstFoldingRange`] spans.
enum TypstFoldingKind {
  /// `{ ... }`
  codeBlock,

  /// `[ ... ]`
  contentBlock,

  /// A function call's argument list: `f(...)`.
  args,

  /// `(1, 2, 3)`
  array,

  /// `(key: value, ...)`
  dict,

  /// `/* ... */`
  comment,
}

/// A collapsible region of Typst source — a code block, content block,
/// array/dict literal, function call's argument list, or block comment.
///
/// Pure syntax, like [`HighlightNode`]: computed directly from whatever
/// `source` the caller passes, with no dependency on a compiled World.
/// Unlike [`CompletionResult`]/[`HoverResult`] there is no `generation` to
/// check against staleness — call it again with the current buffer and the
/// result is already current for it.
class TypstFoldingRange {
  /// Start of the region, in UTF-16 code units — inclusive of the opening
  /// delimiter (e.g. the `{` of a code block).
  final int startUtf16;

  /// End of the region, in UTF-16 code units — inclusive of the closing
  /// delimiter (e.g. the `}` of a code block).
  final int endUtf16;
  final TypstFoldingKind kind;

  const TypstFoldingRange({
    required this.startUtf16,
    required this.endUtf16,
    required this.kind,
  });

  @override
  int get hashCode => startUtf16.hashCode ^ endUtf16.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstFoldingRange &&
          runtimeType == other.runtimeType &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          kind == other.kind;
}

/// Documentation for a function, for an IntelliSense-style details panel
/// shown alongside the completion list.
///
/// Only covers Typst's built-in (native/element) functions — resolving a
/// user-defined closure or a name reached through more than one level of
/// field access (e.g. `a.b.c`) is out of scope, and callers should treat a
/// `None` result as "no details available", not an error.
class TypstFunctionInfo {
  /// The function's name, e.g. `"rect"`.
  final String name;

  /// A synthesized call signature (e.g. `rect(width?:, height?:, fill?:,
  /// body)`), broken into styleable pieces — see [`TypstSignatureToken`].
  /// Cheap to compute and always present when a function resolves, unlike
  /// `description`/`example`.
  final List<TypstSignatureToken> signature;

  /// The function's documentation, as Markdown, with the `example`
  /// section (see `example`) removed. Absent for functions Typst doesn't
  /// carry documentation for (e.g. plugin functions).
  final String? description;

  /// Example Typst source demonstrating the function, extracted from its
  /// documentation's ` ```example ` fenced block, when it has one.
  final String? example;

  /// A syntax-highlighting tree for `example` (see [`HighlightNode`]),
  /// computed the same way [`crate::api::session::TypstSession::highlight`]
  /// would for it — present exactly when `example` is.
  final HighlightNode? exampleHighlight;

  const TypstFunctionInfo({
    required this.name,
    required this.signature,
    this.description,
    this.example,
    this.exampleHighlight,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      signature.hashCode ^
      description.hashCode ^
      example.hashCode ^
      exampleHighlight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstFunctionInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          signature == other.signature &&
          description == other.description &&
          example == other.example &&
          exampleHighlight == other.exampleHighlight;
}

/// One piece of a [`TypstFunctionInfo::signature`], carrying enough
/// structure for a caller to color a function's name differently from its
/// parameter names and punctuation, without having to parse the signature
/// back out of a flat string.
class TypstSignatureToken {
  final String text;
  final TypstSignatureTokenKind kind;

  const TypstSignatureToken({required this.text, required this.kind});

  @override
  int get hashCode => text.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstSignatureToken &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          kind == other.kind;
}

enum TypstSignatureTokenKind {
  /// The function's own name.
  name,

  /// A parameter's name.
  param,

  /// Parens, commas, colons, `?`, `..` — everything that isn't a name.
  punctuation,
}

@freezed
sealed class TypstTooltip with _$TypstTooltip {
  const TypstTooltip._();

  /// Plain text.
  const factory TypstTooltip.text({required String content}) =
      TypstTooltip_Text;

  /// A string of Typst code, e.g. a function signature — callers may want
  /// to render this in a monospace/code style.
  const factory TypstTooltip.code({required String content}) =
      TypstTooltip_Code;
}

@freezed
sealed class TypstrxError with _$TypstrxError implements FrbException {
  const TypstrxError._();

  /// The passed generation no longer identifies the latest compiled
  /// document. The caller should drop the request silently.
  const factory TypstrxError.stale() = TypstrxError_Stale;

  /// No document has been compiled successfully yet.
  const factory TypstrxError.noDocument() = TypstrxError_NoDocument;

  /// The page index is out of bounds for the compiled document.
  const factory TypstrxError.pageOutOfRange({required int pageCount}) =
      TypstrxError_PageOutOfRange;

  /// The requested render exceeds the pixel budget.
  const factory TypstrxError.renderTooLarge({required String message}) =
      TypstrxError_RenderTooLarge;

  /// Any other failure, e.g. an invalid virtual file path.
  const factory TypstrxError.other({required String message}) =
      TypstrxError_Other;
}
