// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// The outcome of a compilation. Returned for both successful and failed
/// compiles; `success` tells them apart and `diagnostics` carries errors and
/// warnings in both cases.
class CompileResult {
  /// Identifies the compiled document. Subsequent render/text calls must
  /// pass this value and fail with [`TypstrxError::Stale`] once a newer
  /// compilation has completed.
  final BigInt generation;

  /// Whether a document was produced. On failure the previous document (if
  /// any) stays available under its own generation.
  final bool success;

  /// Per-page sizes of the compiled document. Empty on failure.
  final List<PageInfo> pages;

  /// Errors and warnings emitted by the compiler.
  final List<TypstDiagnostic> diagnostics;

  /// Wall-clock compilation time in milliseconds.
  final BigInt elapsedMs;

  const CompileResult({
    required this.generation,
    required this.success,
    required this.pages,
    required this.diagnostics,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      generation.hashCode ^
      success.hashCode ^
      pages.hashCode ^
      diagnostics.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          success == other.success &&
          pages == other.pages &&
          diagnostics == other.diagnostics &&
          elapsedMs == other.elapsedMs;
}

/// Severity of a [`TypstDiagnostic`].
enum DiagnosticSeverity { error, warning }

/// One node of a syntax-highlighting tree for Typst source.
///
/// Mirrors the shape of the parse tree: a node with `children` is a grouping
/// construct (e.g. strong emphasis, a heading) and its own `text` is empty; a
/// node with no children is a leaf and `text` is its literal source text.
/// Concatenating every leaf's `text` in tree order reproduces the exact
/// source that was highlighted, so offsets never need to cross the bridge —
/// a caller can track them by summing leaf text lengths while walking.
class HighlightNode {
  /// The highlighting category, if any. `None` for plain/ungrouped nodes.
  final HighlightTag? tag;

  /// This node's literal text, non-empty only for leaves.
  final String text;

  /// Child nodes, non-empty only for non-leaves.
  final List<HighlightNode> children;

  const HighlightNode({this.tag, required this.text, required this.children});

  @override
  int get hashCode => tag.hashCode ^ text.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightNode &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          text == other.text &&
          children == other.children;
}

/// A syntax-highlighting category, mirroring `typst_syntax::Tag`.
enum HighlightTag {
  comment,
  punctuation,
  escape,
  strong,
  emph,
  link,
  raw,
  label,
  ref,
  heading,
  listMarker,
  listTerm,
  mathDelimiter,
  mathOperator,
  mathGroupingParens,
  keyword,
  operator_,
  number,
  string,
  function,
  interpolated,
  error,
}

/// A link region on a page. Either `url` or the `dest_*` fields are set.
class LinkData {
  final RectPt rect;

  /// External URL, if this is a web link.
  final String? url;

  /// Target page (1-based) for an internal link.
  final int? destPage;

  /// Target x position on the destination page in points.
  final double? destXPt;

  /// Target y position on the destination page in points.
  final double? destYPt;

  const LinkData({
    required this.rect,
    this.url,
    this.destPage,
    this.destXPt,
    this.destYPt,
  });

  @override
  int get hashCode =>
      rect.hashCode ^
      url.hashCode ^
      destPage.hashCode ^
      destXPt.hashCode ^
      destYPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkData &&
          runtimeType == other.runtimeType &&
          rect == other.rect &&
          url == other.url &&
          destPage == other.destPage &&
          destXPt == other.destXPt &&
          destYPt == other.destYPt;
}

/// Size of a single page in typographic points (1/72 inch).
class PageInfo {
  final double widthPt;
  final double heightPt;

  const PageInfo({required this.widthPt, required this.heightPt});

  @override
  int get hashCode => widthPt.hashCode ^ heightPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          widthPt == other.widthPt &&
          heightPt == other.heightPt;
}

/// Text and link geometry of one page.
class PageTextData {
  /// The page's text in visual reading order, lines separated by `\n`.
  final String fullText;

  /// One rect per UTF-16 code unit of `full_text` (so the list indexes the
  /// text as a Dart `String`). Newline separators have zero-width rects.
  final List<RectPt> charRects;

  /// Consecutive runs of `full_text` with their bounds; fragments cover the
  /// whole text without gaps.
  final List<TextFragmentData> fragments;

  /// Links on the page.
  final List<LinkData> links;

  const PageTextData({
    required this.fullText,
    required this.charRects,
    required this.fragments,
    required this.links,
  });

  @override
  int get hashCode =>
      fullText.hashCode ^
      charRects.hashCode ^
      fragments.hashCode ^
      links.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageTextData &&
          runtimeType == other.runtimeType &&
          fullText == other.fullText &&
          charRects == other.charRects &&
          fragments == other.fragments &&
          links == other.links;
}

/// A rectangle in page coordinates: typographic points, top-left origin,
/// y-down (`top <= bottom`).
class RectPt {
  final double left;
  final double top;
  final double right;
  final double bottom;

  const RectPt({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ right.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RectPt &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}

/// A rendered tile of a page: straight RGBA8888 pixels, `width * height * 4`
/// bytes, rows top-to-bottom.
class RenderedRegion {
  final int width;
  final int height;
  final Uint8List pixels;

  const RenderedRegion({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderedRegion &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// Configuration for creating a Typst session.
class SessionOptions {
  /// Directory where downloaded `@preview` packages are cached. When `None`,
  /// the platform's standard Typst cache directory is used (which may not be
  /// writable on mobile platforms — pass an app-specific directory there).
  final String? packageCacheDir;

  /// Whether `@preview` packages may be downloaded from the network. Cached
  /// packages keep working when this is `false`.
  final bool allowPackageDownload;

  const SessionOptions({
    this.packageCacheDir,
    required this.allowPackageDownload,
  });

  static Future<SessionOptions> default_() =>
      RustLib.instance.api.crateApiTypesSessionOptionsDefault();

  @override
  int get hashCode => packageCacheDir.hashCode ^ allowPackageDownload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOptions &&
          runtimeType == other.runtimeType &&
          packageCacheDir == other.packageCacheDir &&
          allowPackageDownload == other.allowPackageDownload;
}

/// A text run: `full_text[index..index + length]` (UTF-16 indices).
class TextFragmentData {
  final int index;
  final int length;
  final RectPt bounds;

  const TextFragmentData({
    required this.index,
    required this.length,
    required this.bounds,
  });

  @override
  int get hashCode => index.hashCode ^ length.hashCode ^ bounds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextFragmentData &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          length == other.length &&
          bounds == other.bounds;
}

/// A compiler error or warning.
///
/// Source positions are only resolved for spans that point into the main
/// source (not into packages or other files) and are `None` otherwise.
/// `utf16_start`/`utf16_end` index the main source as a Dart `String`.
class TypstDiagnostic {
  final DiagnosticSeverity severity;
  final String message;
  final List<String> hints;

  /// Start offset into the main source in UTF-16 code units.
  final int? utf16Start;

  /// End offset into the main source in UTF-16 code units.
  final int? utf16End;

  /// 1-based line of the start offset.
  final int? line;

  /// 1-based column (in UTF-16 code units) of the start offset.
  final int? column;

  const TypstDiagnostic({
    required this.severity,
    required this.message,
    required this.hints,
    this.utf16Start,
    this.utf16End,
    this.line,
    this.column,
  });

  @override
  int get hashCode =>
      severity.hashCode ^
      message.hashCode ^
      hints.hashCode ^
      utf16Start.hashCode ^
      utf16End.hashCode ^
      line.hashCode ^
      column.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstDiagnostic &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          message == other.message &&
          hints == other.hints &&
          utf16Start == other.utf16Start &&
          utf16End == other.utf16End &&
          line == other.line &&
          column == other.column;
}

@freezed
sealed class TypstrxError with _$TypstrxError implements FrbException {
  const TypstrxError._();

  /// The passed generation no longer identifies the latest compiled
  /// document. The caller should drop the request silently.
  const factory TypstrxError.stale() = TypstrxError_Stale;

  /// No document has been compiled successfully yet.
  const factory TypstrxError.noDocument() = TypstrxError_NoDocument;

  /// The page index is out of bounds for the compiled document.
  const factory TypstrxError.pageOutOfRange({required int pageCount}) =
      TypstrxError_PageOutOfRange;

  /// The requested render exceeds the pixel budget.
  const factory TypstrxError.renderTooLarge({required String message}) =
      TypstrxError_RenderTooLarge;

  /// Any other failure, e.g. an invalid virtual file path.
  const factory TypstrxError.other({required String message}) =
      TypstrxError_Other;
}
