// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// The outcome of a compilation. Returned for both successful and failed
/// compiles; `success` tells them apart and `diagnostics` carries errors and
/// warnings in both cases.
class CompileResult {
  /// Identifies the compiled document. Subsequent render/text calls must
  /// pass this value and fail with [`TypstrxError::Stale`] once a newer
  /// compilation has completed.
  final BigInt generation;

  /// Whether a document was produced. On failure the previous document (if
  /// any) stays available under its own generation.
  final bool success;

  /// Per-page sizes of the compiled document. Empty on failure.
  final List<PageInfo> pages;

  /// Errors and warnings emitted by the compiler.
  final List<TypstDiagnostic> diagnostics;

  /// Wall-clock compilation time in milliseconds.
  final BigInt elapsedMs;

  const CompileResult({
    required this.generation,
    required this.success,
    required this.pages,
    required this.diagnostics,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      generation.hashCode ^
      success.hashCode ^
      pages.hashCode ^
      diagnostics.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          success == other.success &&
          pages == other.pages &&
          diagnostics == other.diagnostics &&
          elapsedMs == other.elapsedMs;
}

/// Severity of a [`TypstDiagnostic`].
enum DiagnosticSeverity { error, warning }

/// Size of a single page in typographic points (1/72 inch).
class PageInfo {
  final double widthPt;
  final double heightPt;

  const PageInfo({required this.widthPt, required this.heightPt});

  @override
  int get hashCode => widthPt.hashCode ^ heightPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          widthPt == other.widthPt &&
          heightPt == other.heightPt;
}

/// A rendered tile of a page: straight RGBA8888 pixels, `width * height * 4`
/// bytes, rows top-to-bottom.
class RenderedRegion {
  final int width;
  final int height;
  final Uint8List pixels;

  const RenderedRegion({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderedRegion &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// Configuration for creating a Typst session.
class SessionOptions {
  /// Directory where downloaded `@preview` packages are cached. When `None`,
  /// the platform's standard Typst cache directory is used (which may not be
  /// writable on mobile platforms — pass an app-specific directory there).
  final String? packageCacheDir;

  /// Whether `@preview` packages may be downloaded from the network. Cached
  /// packages keep working when this is `false`.
  final bool allowPackageDownload;

  const SessionOptions({
    this.packageCacheDir,
    required this.allowPackageDownload,
  });

  static Future<SessionOptions> default_() =>
      RustLib.instance.api.crateApiTypesSessionOptionsDefault();

  @override
  int get hashCode => packageCacheDir.hashCode ^ allowPackageDownload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOptions &&
          runtimeType == other.runtimeType &&
          packageCacheDir == other.packageCacheDir &&
          allowPackageDownload == other.allowPackageDownload;
}

/// A compiler error or warning.
///
/// Source positions are only resolved for spans that point into the main
/// source (not into packages or other files) and are `None` otherwise.
/// `utf16_start`/`utf16_end` index the main source as a Dart `String`.
class TypstDiagnostic {
  final DiagnosticSeverity severity;
  final String message;
  final List<String> hints;

  /// Start offset into the main source in UTF-16 code units.
  final int? utf16Start;

  /// End offset into the main source in UTF-16 code units.
  final int? utf16End;

  /// 1-based line of the start offset.
  final int? line;

  /// 1-based column (in UTF-16 code units) of the start offset.
  final int? column;

  const TypstDiagnostic({
    required this.severity,
    required this.message,
    required this.hints,
    this.utf16Start,
    this.utf16End,
    this.line,
    this.column,
  });

  @override
  int get hashCode =>
      severity.hashCode ^
      message.hashCode ^
      hints.hashCode ^
      utf16Start.hashCode ^
      utf16End.hashCode ^
      line.hashCode ^
      column.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstDiagnostic &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          message == other.message &&
          hints == other.hints &&
          utf16Start == other.utf16Start &&
          utf16End == other.utf16End &&
          line == other.line &&
          column == other.column;
}

@freezed
sealed class TypstrxError with _$TypstrxError implements FrbException {
  const TypstrxError._();

  /// The passed generation no longer identifies the latest compiled
  /// document. The caller should drop the request silently.
  const factory TypstrxError.stale() = TypstrxError_Stale;

  /// No document has been compiled successfully yet.
  const factory TypstrxError.noDocument() = TypstrxError_NoDocument;

  /// The page index is out of bounds for the compiled document.
  const factory TypstrxError.pageOutOfRange({required int pageCount}) =
      TypstrxError_PageOutOfRange;

  /// The requested render exceeds the pixel budget.
  const factory TypstrxError.renderTooLarge({required String message}) =
      TypstrxError_RenderTooLarge;

  /// Any other failure, e.g. an invalid virtual file path.
  const factory TypstrxError.other({required String message}) =
      TypstrxError_Other;
}
